/** @deprecated Import from appConfig.ts */
export {
  UVWSTACK_UPDATE_REPO as ORBIT_UPDATE_REPO,
  UVWSTACK_UPDATE_REPO_DISPLAY as ORBIT_UPDATE_REPO_DISPLAY,
  UVWSTACK_UPDATE_REPO,
  UVWSTACK_UPDATE_REPO_DISPLAY,
} from './appConfig';
